---
- name: Install nginx
  yum: name={{item}} state=present
  with_items:
  - nginx

- name: Copy NGINX configs... (+Drupal+PHP-FPM)
  copy:
    src: ./
    dest: /etc/nginx/
    owner: root
    mode: 600

- name: Ensure NGINX starts boot time
  service: name=nginx enabled=yes
